on:
  push:
    branches:
      - master

jobs:
  deploy-gcp-function:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authentication on Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/28240645297/locations/global/workloadIdentityPools/bot-assistant-identity-pool/providers/github'
        service_account: 'bot-assistant-deployer-v3@bot-assistant-389822.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'bot-assistant-handler'
        runtime: 'python39'
        entry_point: 'hello_http'
